# Generated by Django 3.2 on 2021-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('unique_squirrel_id', models.CharField(help_text='Unique id of squirrel', max_length=100, primary_key=True, serialize=False)),
                ('X', models.FloatField(default=None, help_text='Latitude', max_length=100)),
                ('Y', models.FloatField(default=None, help_text='Longitude', max_length=100)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Occur before or after noon', max_length=2)),
                ('date', models.DateField(blank=True, default=None, help_text='Occur Date')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel_Adult or Juvenile', max_length=10)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Choose the primary fur color for the squirrel', max_length=15)),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location of squirrel, choose from options', max_length=30)),
                ('specific_location', models.TextField(blank=True, help_text='Additional location information')),
                ('running', models.BooleanField(default=False, help_text='Is squirrel seen running')),
                ('chasing', models.BooleanField(default=False, help_text='Is squirrel seen chasing')),
                ('climbing', models.BooleanField(default=False, help_text='Is squirrel seen climbing')),
                ('eating', models.BooleanField(default=False, help_text='Is squirrel seen eating')),
                ('foraging', models.BooleanField(default=False, help_text='Is squirrel seen foraging')),
                ('other_activities', models.TextField(blank=True, help_text='Additional activities information')),
                ('kuks', models.BooleanField(default=False, help_text='Is squirrel seen kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Is squirrel seen quaas')),
                ('moans', models.BooleanField(default=False, help_text='Is squirrel seen moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Is squirrel flaging tail')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Is squirrel twitching tail')),
                ('approaches', models.BooleanField(default=False, help_text='Is squirrel approaching human')),
                ('indifferent', models.BooleanField(default=False, help_text='Is squirrel indifferent with human')),
                ('runs_from', models.BooleanField(default=False, help_text='Is squirrel avoiding human')),
            ],
        ),
    ]
