# Generated by Django 3.2 on 2021-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.FloatField(blank=True, default=None, help_text='Latitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.FloatField(blank=True, default=None, help_text='Longitude', max_length=100),
        ),
    ]
