# Generated by Django 3.2 on 2021-04-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210410_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel_Adult or Juvenile', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Choose the primary fur color for the squirrel', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.TextField(default=None, help_text='Additional location information'),
        ),
    ]
