# Generated by Django 3.2 on 2021-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_squirrel_other_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.FloatField(default=None, help_text='Latitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.FloatField(default=None, help_text='Longitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel_Adult or Juvenile', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default=None, help_text='Occur Date'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location of squirrel, choose from options', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.TextField(blank=True, default=None, help_text='Additional activities information', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Choose the primary fur color for the squirrel', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', help_text='Occur before or after noon', max_length=2),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.TextField(default=None, help_text='Additional location information', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(default=None, help_text='Unique id of squirrel', max_length=100, primary_key=True, serialize=False),
        ),
    ]
