# Generated by Django 3.2 on 2021-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210410_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.FloatField(default=None, help_text='Longitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.FloatField(default=None, help_text='Latitude', max_length=100),
        ),
    ]
