# Generated by Django 3.1.7 on 2021-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210413_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, default=None, help_text='Occur Date', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.TextField(blank=True, default=None, help_text='Additional location information', null=True),
        ),
    ]
